### ISSUE TITLE
Add to log more details about upload\download content

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/wordpress-localization-plugin#145]
*Discovered during testing #144*

I researched bug with download file and didn't find anything useful in our logs. Tons of sql queries which cannot be muted temporary, and no info about processed fields ([WP log example.txt](https://github.com/Smartling/wordpress-localization-plugin/files/19661/log.exampl.txt)). Compare it with  [CQ file download log.txt](https://github.com/Smartling/wordpress-localization-plugin/files/19682/CQ.file.download.log.txt)

**DoD**:
1. Add into log details about Upload and Download content
 * How many fields, probably list of fileds
 * What handler will be used for fileds
 * Name of field if it will be excluded
2. Ability to disable logging partially or use different levels. An example: INFO for DB logs; DEBUG for upload; WARN for everything else
 * Looks like monolog uses `channels` for this
 * Not familiar with monolog but can show how configuration can look in log4j
```xml
    <logger name="com.smartling.db" level="INFO" additivity="false">
        <appender-ref ref="CONSOLE"/>
    </logger>
    <logger name="com.smartling.upload" level="DEBUG" additivity="false">
        <appender-ref ref="CONSOLE"/>
    </logger>
    <root level="WARN">
        <appender-ref ref="CONSOLE"/>
    </root>
```
 * I mean all new channels will use the same handler (same log file) but we will be able to configure different log levels. According to [this documentation](http://symfony.com/doc/current/reference/dic_tags.html#monolog-logger) it should look like
```yaml
  wrapper.entity.menu:
    class: Smartling\DbAl\WordpressContentEntities\MenuEntity
    arguments:
      - "@logger"
    tags:
      - { name: monolog.logger, channel: db }
  ...
  manager.submission:
    class: Smartling\Submissions\SubmissionManager
    arguments:
     - "@logger"
     - "@site.db"
     - "%submission.pagesize%"
     - "@entity.helper"
    tags:
      - { name: monolog.logger, channel: submissions }
 ...
```
